djangocrm/clients/urls.py
from django.urls import path
from . import views


app_mame = 'clients'

urlpatterns = [
    path("add_client/", views.add_client, name="add_client"),
    path("view_client/<int:pk>/", views.view_client, name="view_client"),
    path("delete_client/<int:pk>/", views.del_client, name="del_client"),
    path("edit/<int:pk>/", views.update_info, name="update_info"),
    path("send/<int:id>/", views.send_message, name="send_message"),
    # path("edit/<int:pk>/", views.UpdateRecordView.as_view(), name="update_info")
]

djangocrm/djangocrm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('team.urls')),
    path('clients/', include(('clients.urls', 'clients'), namespace='clients')),
    # path('clients/', include('clients.urls', namespace='clients')),
]

djangocrm/team/urls.py
from django.urls import path
from . import views

app_mame = 'team'

urlpatterns = [
    path("", views.singin, name="login"),
    path("registration/", views.registration_team, name="registration_team"),
    path("home/", views.home, name="home"),
    path("add_user/", views.add_user, name="add_user"),
    path("logout/", views.log_out, name="log_out"),
    path("home/view_user_clients/<int:id>/", views.view_user_clients, name="view_user_clients"),
]

djangocrm/clients/models.py
from django.db import models
from django.contrib.auth.models import User

class Client(models.Model):
    name = models.CharField(max_length=128)
    phone = models.CharField(max_length=128)
    email = models.EmailField(max_length=256) 
    description = models.TextField()
    worker = models.CharField(max_length=128)
    data = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return f'Клиент {self.name}'
    
    
    

djangocrm/clients/forms.py
from django import forms
from .models import Client
from team.models import UserModel


class AddClientForm(forms.ModelForm):

    email = forms.CharField(required=False,
        label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Email'})
    )
    name = forms.CharField(
        label="", max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'*Имя'})
    )
    description = forms.CharField(
        label="", widget=forms.Textarea(attrs={'class':'form-control', 'placeholder':'Комментарии'})
    )  
    phone = forms.CharField(
        label="", max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'8-000-000-00-00'})
    )

    worker = forms.ModelChoiceField(
        label="Выберите сотрудника", queryset=UserModel.objects.none(), widget=forms.Select(attrs={'class':'form-control', 'placeholder':'Имя Сотрудника'})
    ) 

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(AddClientForm, self).__init__(*args, **kwargs)
        self.fields['worker'].queryset = UserModel.objects.filter(user_id=user)

    class Meta:
        model = Client
        fields = ['name', 'phone', 'email', 'description', 'worker']

djangocrm/clients/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import Client
from .forms import AddClientForm


@login_required
def add_client(request):
    if request.method == 'POST':
        form = AddClientForm(request.POST, user=request.user)
        if form.is_valid():
            new_client = form.save(commit=False)
            new_client.user = request.user
            new_client.save()
            messages.success(request, 'Новая запись добавлена!')
            return redirect('home')
    else:
        form = AddClientForm(user=request.user)
    return render(request, 'clients/add_client.html', {'form': form})


@login_required
def view_client(request, pk):
    client = Client.objects.filter(pk=pk, user=request.user)
    return render(request, 'clients/view_client.html', {'client': client})


@login_required
def update_info(request, pk):
    client = get_object_or_404(Client, pk=pk, user=request.user)

    if request.method == 'GET':
        context = {
            'form': AddClientForm(instance=client, user=request.user), 'pk': pk
        }
        return render(request, 'clients/update_client.html', context)
    if request.method == 'POST':
        form = AddClientForm(request.POST, instance=client, user=request.user)
        if form.is_valid():
            new_client = form.save(commit=False)
            new_client.user = request.user
            new_client.save()
            messages.success(request, 'Запись изменена!')
            return redirect('home')
    return render(request, 'clients/update_client.html', {'form': form})


@login_required
def del_client(request, pk):
    client = Client.objects.filter(pk=pk, user=request.user)
    if request.method == 'POST':
        client.delete()
        messages.success(request, 'Запись удалена!')
        return redirect('home')


def send_message(request, id):
    client = Client.objects.get(id=id, user=request.user)
    phone_number = client.phone
    for i in ' +()-':
        if i in phone_number:
            phone_number = phone_number.replace(i, '')
    return redirect(f'https://web.whatsapp.com/send?phone={phone_number}')

djangocrm/clients/templates/clients/add_client.html
{% extends 'team/base.html' %}

{% block content %}
<div class="col-md-6 offset-md-3">
	<h1>Новая запись</h1>
	<br/>
	<form method="POST" action="{% url 'clients:add_client' %}">
    {% csrf_token %}
    {{ form.as_p }} 
    <br/>
      <button type="submit" class="btn btn-secondary">Добавить</button>
       <a href="{% url 'home' %}" class="btn btn-secondary">Назад</a>   
  </form>    
</div>   
{% endblock %}

djangocrm/clients/templates/clients/update_client.html
{% extends 'team/base.html' %}

{% block content %}
<div class="col-md-6 offset-md-3">
	<h1>Редактирование</h1>
	<br/>
	<form method="POST" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <br/>
      <button type="submit" class="btn btn-secondary" value="Save">Сохранить</button>
      <a href="{% url 'home' %}" class="btn btn-secondary">Назад</a>   
  </form>
  <br/>
  <br/>
</div>   
{% endblock %}

djangocrm/clients/templates/clients/view_client.html
{% extends 'team/base.html' %}

{% block content %}

{% for i in client %}
<table class="table table-striped table-hover table-bordered">
  <thead class="table-dark">
    <tr>
    <th scope="col">Имя</th>
    <th scope="col">Телефон</th>
    <th scope="col">Email</th>
    <th scope="col">Дата</th>
    </tr>
  </thead>
  <tbody>
    <tr>
    <td>{{ i.name }}</td>
    <td>{{ i.phone }}</td>
    <td>{{ i.email }}</td>
    <td>{{ i.data }}</td>
    </tr>
  </tbody>
</table>
<table style="table-layout: fixed; width: 100%" class="table table-striped table-hover table-bordered">
  <thead class="table-dark">
    <tr>
    <th scope="col">Описание</th>
    </tr>
  </thead>
  <tbody>
    <tr>
    <td style="word-wrap:break-word">{{ i.description|safe }}</td>
    </tr>
  </tbody>
</table>

<br/>
  <a href="{% url 'clients:update_info' i.id %}" type="button" class="btn btn-secondary">Изменить</a>
  <a href="{% url 'clients:send_message' i.id %}" type="button" class="btn btn-secondary">Написать в Whatsapp</a> 
<br/>
<br/>
<form method="POST" action="{% url 'clients:del_client' i.id %}">
{% csrf_token %}
  <button type="submit" class="btn btn-secondary">Удалить</button>
</form> 

{% endfor %}
{% endblock  %}