djangocrm/clients/urls.py
from django.urls import path
from . import views


app_mame = 'clients'

urlpatterns = [
    path("add_client/", views.add_client, name="add_client"),
    path("view_client/<int:pk>/", views.view_client, name="view_client"),
    path("delete_client/<int:pk>/", views.del_client, name="del_client"),
    path("edit/<int:pk>/", views.update_info, name="update_info"),
    path("send/<int:id>/", views.send_message, name="send_message"),
    # path("edit/<int:pk>/", views.UpdateRecordView.as_view(), name="update_info")
]

djangocrm/djangocrm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('team.urls')),
    path('clients/', include(('clients.urls', 'clients'), namespace='clients')),
    # path('clients/', include('clients.urls', namespace='clients')),
]

djangocrm/team/urls.py
from django.urls import path
from . import views

app_mame = 'team'

urlpatterns = [
    path("", views.singin, name="login"),
    path("registration/", views.registration_team, name="registration_team"),
    path("home/", views.home, name="home"),
    path("add_user/", views.add_user, name="add_user"),
    path("logout/", views.log_out, name="log_out"),
    path("home/view_user_clients/<int:id>/", views.view_user_clients, name="view_user_clients"),
]

djangocrm/team/models.py
from django.db import models
from django.contrib.auth.models import User


class UserModel(models.Model):
    first_name = models.CharField(max_length=128)
    last_name = models.CharField(max_length=128)
    phone = models.CharField(max_length=128)
    email = models.EmailField(max_length=256)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'user'

    def __str__(self) -> str:
        return self.first_name

djangocrm/team/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django import forms
from .models import UserModel


class SignUpForm(UserCreationForm):
    email = forms.EmailField(
        label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Email Address'})
    )
    username = forms.CharField(
        label="", max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Username'})
    )
    password1 = forms.CharField(
        label="", max_length=100, widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'Password'})
    )
    password2 = forms.CharField(
        label="", max_length=100, widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'Password confirmation'})
    )

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class AddUserForm(forms.ModelForm):
    email = forms.EmailField(
        label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Email Address'})
    )
    first_name = forms.CharField(
        label="", max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'*First_name'})
    )
    last_name = forms.CharField(
        label="", max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'*Last_name'})
    )  
    phone = forms.CharField(
        label="", max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'8-000-000-00-00'})
    ) 
        
    class Meta:
        model = UserModel
        fields = ['first_name', 'last_name', 'phone', 'email']

    
class LoginUserForm(AuthenticationForm):
    username = forms.CharField(
        label="", max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Username'})
    )
    password = forms.CharField(
        label="", max_length=100, widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'Password'})
    )
    class Meta:
        model = User
        fields = ['username', 'password']

djangocrm/team/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.core.paginator import Paginator
from django.contrib import messages
from .forms import SignUpForm, AddUserForm, LoginUserForm
from clients.models import Client
from team.models import UserModel


def singin(request):
    if request.user.is_authenticated:
        return redirect('home')
    elif request.method == 'POST':
        form = LoginUserForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
                return redirect('home')
    else:
        form = LoginUserForm()
    return render(request, 'team/login.html', {'form': form})


def registration_team(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.save()

            username = form.cleaned_data['username']
            password = form.cleaned_data.get('password1')

            user = authenticate(username=username, password=password)
            login(request, user)
            messages.success(request, 'Вы успешно зарегистированы!')
            return redirect('home')
    else:
        form = SignUpForm()
    return render(request, 'team/registration.html', {'form': form})


@login_required
def home(request):
    clients = Client.objects.filter(user=request.user).order_by('-data')
    paginator = Paginator(clients, 25)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    workers = UserModel.objects.filter(user=request.user)
    return render(
        request, 'team/home.html', {'page_obj': page_obj, 'workers': workers}
    )


@login_required
def add_user(request):
    if request.method == 'POST':
        form = AddUserForm(request.POST)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.user = request.user
            new_user.save()
            messages.success(request, 'Сотрудник добавлен')
            return redirect('home')
    else:
        form = AddUserForm()
    return render(request, 'team/add_user.html', {'form': form})


def view_user_clients(request, id):
    user_name = UserModel.objects.get(id=id, user=request.user)
    workers = Client.objects.filter(worker=user_name.first_name)

    paginator = Paginator(workers, 25)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'team/view_user.html', {'page_obj': page_obj})


def log_out(request):
    logout(request)
    return redirect('login')

djangocrm/team/templates/team/add_user.html
{% extends 'team/base.html' %}

{% block content %}
<div class="col-md-6 offset-md-3">
	<h1>Добавить сотрудника</h1>
	<br/>
	<form method="POST" action="{% url 'add_user' %}">
    {% csrf_token %}
    {{ form.as_p }}   
    <br/>
    <button type="submit" class="btn btn-secondary">Добавить</button>
    <a href="{% url 'home' %}" class="btn btn-secondary">Назад</a>   
  </form>    
</div>   
{% endblock %}

djangocrm/team/templates/team/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Django CRM</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  </head>
  <body>
    {% include 'team/navbar.html' %}
    <div class="container">
      <br/>
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-warning alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>


        {% endfor %}
      {% endif %}
      
      {% block content %}
      {% endblock%}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>

djangocrm/team/templates/team/home.html
{% extends 'team/base.html' %}
{% block content %}
<div class="input-group mb-3">
  <select id="user-select" class="form-select" aria-label="Default select example" style="max-width:20%;">
    <option selected disabled>Выбор записей ...</option>
    {% for worker in workers %}
    <option value="{{ worker.id }}">{{ worker }}</option>
    {% endfor %}
  </select>

  <script>
    document.getElementById('user-select').addEventListener('change', function() {
        var chapterId = this.value;
        if (chapterId) {
            var url = "{% url 'view_user_clients' 0 %}".replace('0', chapterId);
            window.location.href = url;
        }
    });
  </script>
</div>

  <table class="table table-striped table-hover table-bordered">
    <thead class="table-dark">
      <tr>
        <th scope="col">Имя</th>
        <th scope="col">Телефон</th>
        <th scope="col">Email</th>
        <th scope="col">Комментарии</th>
        <th scope="col">Сотрудник</th>
        <th scope="col">Дата</th>
        <th scope="col">ID</th>
      </tr>
    </thead>
    <tbody>
      {% if page_obj %}
      {% for client in page_obj %}
        <tr>
        <td>{{ client.name }}</td>
        <td>{{ client.phone }}</td>
        <td>{{ client.email }}</td>
        <td style="word-wrap: break-word">{{ client.description|truncatechars:40 }}</td>
        <td>{{ client.worker }}</td>
        <td>{{ client.data}}</td>
        <td>
          <a href="{% url 'clients:view_client' client.id %}">{{ client.id }}</a>
        </td>
        </tr>
      {% endfor %}
      <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; Первая</a>
                <a href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
            {% endif %}
    
            <span class="current">
                Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}
            </span>
    
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">Следующая</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">Последняя &raquo;</a>
            {% endif %}
        </span>
    </div>
      {% else %}
      <p>Записей нет</p>
    {% endif %}
    </tbody>
  </table>

{% endblock %}

djangocrm/team/templates/team/login.html
{% extends 'team/base.html' %}

{% block content %}
<div class="col-md-6 offset-md-3">
  <h1>Вход</h1>
  <form method=POST action="{% url 'login' %}">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-secondary">Войти</button>
  </form>
</div> 
{% endblock %}

djangocrm/team/templates/team/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    {% if user.is_authenticated %}
    <a class="navbar-brand" href="{% url 'home' %}">CRM {{ request.user }}</a>
    {% else %}
    <a class="navbar-brand" href="">CRM</a>
    {% endif %}
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">       
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home' %}">Записи</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'clients:add_client' %}">Новая запись</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'add_user' %}">Добавить сотрудника</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'log_out' %}">Выход</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'registration_team' %}">Регистрация</a>  
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Вход</a>  
          </li>
        {% endif %}  
      </ul>     
    </div>
  </div>
</nav>

djangocrm/team/templates/team/registration.html
{% extends 'team/base.html' %}

{% block content %}
<div class="col-md-6 offset-md-3">
	<h1>Регистрация</h1>
	<br/>
	
	<form method="POST" action="">
		{% csrf_token %}
		{% if form.errors %}
				<div class="alert alert-warning alert-dismissible fade show" role="alert">
				  Your Form Has Errors
				  {% for field in form %}
					  {% if field.errors %}
						  {{ field.errors }}
					  {% endif %}
				  {% endfor %}
				  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
				</div>
			{% endif %}
	
		{{ form.as_p }}
	
		<br/>
		  <button type="submit" class="btn btn-secondary">Зарегистрировать</button>
		</form>
	</div>
	
	{% endblock %}

djangocrm/team/templates/team/view_user.html
{% extends 'team/base.html' %}
{% block content %}
<a href="{% url 'home' %}" type="button" class="btn btn-secondary">На главную</a> 
<br/>
<br/>
  <table class="table table-striped table-hover table-bordered">
    <thead class="table-dark">
      <tr>
        <th scope="col">Имя</th>
        <th scope="col">Телефон</th>
        <th scope="col">Email</th>
        <th scope="col">Комментарии</th>
        <th scope="col">Сотрудник</th>
        <th scope="col">Дата</th>
        <th scope="col">ID</th>
      </tr>
    </thead>
    <tbody>
      {% if page_obj %}
      {% for client in page_obj %}
        <tr>
        <td>{{ client.name }}</td>
        <td>{{ client.phone }}</td>
        <td>{{ client.email }}</td>
        <td style="word-wrap: break-word">{{ client.description|truncatechars:40 }}</td>
        <td>{{ client.worker }}</td>
        <td>{{ client.data}}</td>
        <td>
          <a href="{% url 'clients:view_client' client.id %}">{{ client.id }}</a>
        </td>
        </tr>
      {% endfor %}
      <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; Первая</a>
                <a href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
            {% endif %}
    
            <span class="current">
                Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}
            </span>
    
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">Следующая</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">Последняя &raquo;</a>
            {% endif %}
        </span>
    </div>
      {% else %}
      <p>Записей нет</p>
    {% endif %}
    </tbody>
  </table>

{% endblock %}